name: "app"
mode: "debug"
start_time: "2022-08-22"
machine_id: 1
Port: 3000

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "ginblog"
  password: "admin123"
  dbname: "ginblog"
  max_open_conns: 200
  max_idle_conns: 50

log:
  level: "debug"
  filename: "app.log"
  max_size: 300
  max_age: 30
  max_backups: 7
